"""AI自动生成小说对话框 - 逐章生成模式"""
import re
import time
import threading
import concurrent.futures
from PySide6.QtCore import Qt, QTimer, QObject, Signal
from PySide6.QtWidgets import (
    QDialog, QVBoxLayout, QHBoxLayout, QWidget,
    QLabel, QLineEdit, QPushButton, QTextEdit, QComboBox,
    QMessageBox, QProgressBar, QFormLayout, QGroupBox, QFrame,
    QTextBrowser, QScrollArea
)
from core.ai_prompts import get_prompt, make_chapter_prompt
from models.ai_provider import ai_manager
from core.writing_core import project_manager, volume_manager, chapter_manager
from utils.config_manager import config_manager
from utils.text_processor import text_processor
from utils.logger import logger

AI_CHAPTER_TIMEOUT = 180


class _GenBridge(QObject):
    """生成进度信号桥接器（跨线程安全）"""
    progress = Signal(int, int, str, int)
    stream_update = Signal(int, int, int, int, str)
    chapter_done = Signal(int, str, int, int)
    finished = Signal(int, str, list)
    error = Signal(str)
    log = Signal(str)
    token_alive = Signal()


class AutoGenerateDialog(QDialog):
    """AI自动生成小说对话框 - 逐章生成模式"""

    def __init__(self, parent=None):
        super().__init__(parent)
        self._generating = False
        self._cancel_requested = False
        self._parent_window = parent
        self._thread = None
        self._bridge = _GenBridge()
        self._chapter_start_time = 0
        self._watchdog_timer = QTimer(self)
        self._watchdog_timer.setInterval(5000)
        self._watchdog_timer.timeout.connect(self._watchdog_check)
        self._completed_chapters = []
        self._pool = concurrent.futures.ThreadPoolExecutor(max_workers=1)
        self._last_token_time = 0.0
        self._current_chapter_future = None
        self._selected_project_id = 0
        self._existing_chapters_cache = []

        self.setWindowTitle("AI自动生成小说")
        self.setMinimumSize(680, 750)
        self.resize(720, 800)
        self.setup_ui()
        self.connect_signals()

    def setup_ui(self):
        layout = QVBoxLayout(self)

        scroll_area = QScrollArea()
        scroll_area.setWidgetResizable(True)
        scroll_area.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        scroll_area.setFrameShape(QFrame.NoFrame)

        scroll_content = QWidget()
        scroll_layout = QVBoxLayout(scroll_content)
        scroll_layout.setContentsMargins(0, 0, 0, 0)

        continue_group = QGroupBox("方式三：基于已有项目续写（在已有小说基础上继续创作）")
        continue_layout = QFormLayout(continue_group)

        self._existing_project = QComboBox()
        self._existing_project.setToolTip("选择已有的小说项目，基于其内容继续生成后续章节")
        continue_layout.addRow("选择已有项目：", self._existing_project)

        range_row = QHBoxLayout()
        range_row.addWidget(QLabel("从第"))
        self._chapter_from = QComboBox()
        self._chapter_from.setMinimumWidth(80)
        range_row.addWidget(self._chapter_from)
        range_row.addWidget(QLabel("章  写到第"))
        self._chapter_to = QComboBox()
        self._chapter_to.setMinimumWidth(80)
        range_row.addWidget(self._chapter_to)
        range_row.addWidget(QLabel("章"))
        range_row.addStretch()
        continue_layout.addRow("章节范围：", range_row)

        self._continue_mode_label = QLabel()
        self._continue_mode_label.setStyleSheet("color: #52C41A; font-weight: bold; font-size: 12px;")
        continue_layout.addRow(self._continue_mode_label)

        scroll_layout.addWidget(continue_group)

        self._existing_project.currentIndexChanged.connect(self._on_existing_project_changed)

        name_group = QGroupBox("小说基本信息（非续写模式时填写）")
        name_form = QFormLayout(name_group)

        self._novel_name = QLineEdit()
        self._novel_name.setPlaceholderText("输入小说名称...")
        name_form.addRow("小说名称：", self._novel_name)

        self._male_name = QLineEdit()
        self._male_name.setPlaceholderText("男主角姓名（可选）")
        name_form.addRow("男主角：", self._male_name)

        self._female_name = QLineEdit()
        self._female_name.setPlaceholderText("女主角姓名（可选）")
        name_form.addRow("女主角：", self._female_name)

        scroll_layout.addWidget(name_group)

        detail_group = QGroupBox("方式一：填写详细设定生成（未填总大纲时使用）")
        detail_form = QFormLayout(detail_group)

        self._novel_type = QComboBox()
        self._novel_type.setEditable(True)
        self._novel_type.addItems(["玄幻", "奇幻", "武侠", "仙侠", "都市", "言情", "历史", "科幻", "悬疑", "恐怖"])
        detail_form.addRow("小说类型：", self._novel_type)

        self._protagonist = QTextEdit()
        self._protagonist.setMaximumHeight(55)
        self._protagonist.setPlaceholderText("例：林夜，22岁普通大学生，性格内向但坚韧，意外获得星际导航能力")
        detail_form.addRow("主角设定：", self._protagonist)

        self._setting = QTextEdit()
        self._setting.setMaximumHeight(55)
        self._setting.setPlaceholderText("例：公元3000年，人类已实现星际航行，银河联邦与外星文明对峙")
        detail_form.addRow("故事背景：", self._setting)

        self._plot = QTextEdit()
        self._plot.setMaximumHeight(70)
        self._plot.setPlaceholderText("例：主角获神秘能力后卷入星际阴谋，发现自己的身世之谜与远古文明有关")
        detail_form.addRow("核心剧情：", self._plot)

        self._outline = QTextEdit()
        self._outline.setMaximumHeight(80)
        self._outline.setPlaceholderText("例：\n第一章：主角意外觉醒能力\n第二章：遭遇第一次危机\n第三章：发现身世线索")
        detail_form.addRow("分章大纲：", self._outline)

        scroll_layout.addWidget(detail_group)

        gender_group = QWidget()
        gender_layout = QHBoxLayout(gender_group)
        gender_layout.setContentsMargins(0, 4, 0, 4)
        gender_layout.addWidget(QLabel("阅读向："))
        self._gender = QComboBox()
        self._gender.addItems(["男频（男主视角，故事围绕男主展开）", "女频（女主视角，故事围绕女主展开）"])
        self._gender.setCurrentIndex(0)
        self._gender.setToolTip("选择男频或女频，决定第一主角的性别和故事叙事视角")
        gender_layout.addWidget(self._gender, 1)
        scroll_layout.addWidget(gender_group)

        style_group = QWidget()
        style_layout = QHBoxLayout(style_group)
        style_layout.setContentsMargins(0, 4, 0, 4)
        style_layout.addWidget(QLabel("文笔风格："))
        self._writing_style = QComboBox()
        self._writing_style.addItems([
            "（默认）",
            "自动文笔 - 根据大纲和主题自动选择最适合的文笔风格",
            "简洁干练型 - 短句为主，叙事直接，节奏明快",
            "华丽繁复型 - 辞藻丰赡，修辞密集，意象层叠，善用比喻通感",
            "细腻写实型 - 细节描写精准，画面感强，真实沉浸",
            "幽默诙谐型 - 轻松活泼，俏皮有趣，带吐槽调侃",
            "冷峻沉郁型 - 冷静克制，语言简洁有力量，氛围压抑",
            "诗意唯美型 - 语言富有韵律，意象优美，意境深远",
            "古风典雅型 - 文言词汇，典雅有韵味，古风十足",
            "通俗口语型 - 口语化表达，自然流畅，接地气",
            "悬疑紧张型 - 短句压迫感，悬念层层递进，氛围紧张",
        ])
        self._writing_style.setCurrentIndex(0)
        self._writing_style.setToolTip("选择AI生成时的文笔风格，影响语言表达方式和叙事节奏")
        style_layout.addWidget(self._writing_style, 1)
        scroll_layout.addWidget(style_group)

        separator = QFrame()
        separator.setFrameShape(QFrame.HLine)
        separator.setFrameShadow(QFrame.Sunken)
        separator.setStyleSheet("color: #DCDCDC; margin: 8px 0;")
        scroll_layout.addWidget(separator)

        outline_group = QGroupBox("方式二：填写总大纲直接生成（填写后方式一自动禁用）")
        outline_layout = QVBoxLayout(outline_group)

        outline_desc = QLabel(
            "总大纲应包含完整的故事设定：世界观、主要人物、各章剧情脉络。"
            "填写总大纲后，将根据总大纲逐章生成，方式一将被忽略。"
        )
        outline_desc.setWordWrap(True)
        outline_desc.setStyleSheet("color: #888; font-size: 12px; padding: 4px 0;")
        outline_layout.addWidget(outline_desc)

        self._master_outline = QTextEdit()
        self._master_outline.setMinimumHeight(140)
        self._master_outline.setPlaceholderText(
            "填写完整的总大纲，例如：\n"
            "【世界观】公元3000年，人类星际时代...\n"
            "【主要人物】林夜：男，22岁，星际导航能力...\n"
            "【剧情脉络】\n"
            "第一卷：觉醒篇（第1-5章）\n"
            "  第一章：意外觉醒 - 林夜在事故中获得能力\n"
            "  第二章：初次测试 - 发现能力远超想象\n"
        )
        outline_layout.addWidget(self._master_outline)

        self._outline_mode_label = QLabel()
        self._outline_mode_label.setAlignment(Qt.AlignRight)
        self._outline_mode_label.setStyleSheet("color: #FA8C16; font-weight: bold; font-size: 12px;")
        outline_layout.addWidget(self._outline_mode_label)

        scroll_layout.addWidget(outline_group)
        scroll_layout.addStretch()

        scroll_area.setWidget(scroll_content)
        layout.addWidget(scroll_area, 1)

        progress_group = QGroupBox("生成进度")
        progress_layout = QVBoxLayout(progress_group)

        self._progress_status = QLabel("等待开始...")
        self._progress_status.setStyleSheet("font-size: 14px; font-weight: bold; color: #4A90D9;")
        progress_layout.addWidget(self._progress_status)

        self._progress_bar = QProgressBar()
        self._progress_bar.setRange(0, 100)
        self._progress_bar.setValue(0)
        progress_layout.addWidget(self._progress_bar)

        info_row = QHBoxLayout()
        self._progress_chapter = QLabel("章节: -")
        self._progress_chapter.setStyleSheet("color: #666;")
        info_row.addWidget(self._progress_chapter)
        info_row.addStretch()
        self._progress_words = QLabel("字数: 0")
        self._progress_words.setStyleSheet("color: #666;")
        info_row.addWidget(self._progress_words)
        progress_layout.addLayout(info_row)

        self._progress_log = QTextBrowser()
        self._progress_log.setMaximumHeight(120)
        self._progress_log.setStyleSheet("font-size: 11px; color: #888;")
        progress_layout.addWidget(self._progress_log)

        progress_group.hide()
        layout.addWidget(progress_group)

        self._status_label = QLabel("")
        self._status_label.setAlignment(Qt.AlignCenter)
        self._status_label.setStyleSheet("color: #4A90D9; font-size: 13px;")
        layout.addWidget(self._status_label)

        btn_layout = QHBoxLayout()
        btn_layout.addStretch()

        self._generate_btn = QPushButton("开始生成 ✨")
        self._generate_btn.setFixedWidth(180)
        self._generate_btn.setStyleSheet(
            "QPushButton { background-color: #4A90D9; color: white; font-weight: bold; "
            "border-radius: 6px; padding: 10px 24px; font-size: 14px; }"
            "QPushButton:hover { background-color: #357ABD; }"
            "QPushButton:disabled { background-color: #aaa; }"
        )
        self._generate_btn.clicked.connect(self.start_generation)
        btn_layout.addWidget(self._generate_btn)

        self._cancel_btn = QPushButton("⏹ 停止生成")
        self._cancel_btn.setFixedWidth(140)
        self._cancel_btn.setEnabled(False)
        self._cancel_btn.setStyleSheet(
            "QPushButton { background-color: #FF4D4F; color: white; font-weight: bold; "
            "border-radius: 6px; padding: 10px 24px; font-size: 14px; }"
            "QPushButton:hover { background-color: #D9363E; }"
            "QPushButton:disabled { background-color: #aaa; }"
        )
        self._cancel_btn.clicked.connect(self.cancel_generation)
        btn_layout.addWidget(self._cancel_btn)

        close_btn = QPushButton("关闭")
        close_btn.setFixedWidth(100)
        close_btn.clicked.connect(self.close)
        btn_layout.addWidget(close_btn)

        layout.addLayout(btn_layout)

        self._master_outline.textChanged.connect(self._on_outline_text_changed)

        self._load_existing_projects()

    def _load_existing_projects(self):
        """加载已有项目列表"""
        self._existing_project.clear()
        self._existing_project.addItem("（不续写，新建小说）", 0)
        try:
            projects = project_manager.get_all_projects()
            for p in projects:
                name = p.get("name", f"项目ID:{p['id']}")
                self._existing_project.addItem(f"{name}", p["id"])
        except Exception as e:
            logger.error(f"加载项目列表失败: {e}")

    def _on_existing_project_changed(self, idx: int):
        """已有项目选择变更"""
        pid = self._existing_project.currentData()
        self._selected_project_id = pid if pid else 0

        # 清除续写模式标签
        self._continue_mode_label.setText("")

        if self._selected_project_id:
            # 加载该项目的章节信息
            from core.writing_core import chapter_manager
            chapters = chapter_manager.get_all_chapters_for_project(self._selected_project_id)
            self._existing_chapters_cache = chapters
            total = len(chapters)

            self._chapter_from.clear()
            self._chapter_to.clear()
            for i, ch in enumerate(chapters, 1):
                label = f"{i} - {ch['title']}"
                self._chapter_from.addItem(label, i)
                self._chapter_to.addItem(label, i)

            if total > 0:
                self._chapter_from.setCurrentIndex(0)
                self._chapter_to.setCurrentIndex(total - 1)

            self._continue_mode_label.setText(
                f"🔗 续写模式已启用：当前共{total}章，将从第{total + 1}章开始续写"
            )
        else:
            self._existing_chapters_cache = []
            self._chapter_from.clear()
            self._chapter_to.clear()

    def connect_signals(self):
        self._bridge.progress.connect(self._on_progress)
        self._bridge.stream_update.connect(self._on_stream_update)
        self._bridge.chapter_done.connect(self._on_chapter_done)
        self._bridge.finished.connect(self._on_generation_finished)
        self._bridge.error.connect(self._on_generation_error)
        self._bridge.log.connect(self._progress_log.append)
        self._bridge.token_alive.connect(self._on_token_alive)

    def _on_outline_text_changed(self):
        has_outline = bool(self._master_outline.toPlainText().strip())
        if has_outline:
            self._outline_mode_label.setText("🔒 总大纲模式已启用，将忽略上方详细设定")
            self._novel_type.setEnabled(False)
            self._protagonist.setEnabled(False)
            self._setting.setEnabled(False)
            self._plot.setEnabled(False)
            self._outline.setEnabled(False)
        else:
            self._outline_mode_label.setText("")
            self._novel_type.setEnabled(True)
            self._protagonist.setEnabled(True)
            self._setting.setEnabled(True)
            self._plot.setEnabled(True)
            self._outline.setEnabled(True)

    def _switch_to_generating_mode(self):
        """切换到生成中模式"""
        self._generating = True
        self._cancel_requested = False

        self._generate_btn.setEnabled(False)
        self._generate_btn.setText("生成中...")
        self._cancel_btn.setEnabled(True)

        for widget in self.findChildren(QGroupBox):
            widget.setEnabled(False)

        self._novel_name.setEnabled(False)
        self._male_name.setEnabled(False)
        self._female_name.setEnabled(False)

        progress_group = self.findChildren(QGroupBox)
        target = [w for w in progress_group if w.title() == "生成进度"]
        if target:
            target[0].show()
            target[0].setEnabled(True)

        self._progress_bar.setValue(0)
        self._progress_status.setText("正在准备生成...")
        self._progress_log.clear()
        self._completed_chapters = []
        self._chapter_start_time = 0
        self._last_token_time = time.time()
        self._watchdog_timer.start()

    def _switch_to_idle_mode(self):
        """切换回空闲模式"""
        self._generating = False
        self._cancel_requested = False
        self._cancel_btn.setEnabled(False)
        self._watchdog_timer.stop()

        self._generate_btn.setEnabled(True)
        self._generate_btn.setText("开始生成 ✨")

        for widget in self.findChildren(QGroupBox):
            widget.setEnabled(True)
        self._novel_name.setEnabled(True)
        self._male_name.setEnabled(True)
        self._female_name.setEnabled(True)

        progress_group = [w for w in self.findChildren(QGroupBox) if w.title() == "生成进度"]
        if progress_group:
            progress_group[0].hide()

    def start_generation(self):
        if self._generating:
            return

        is_continuation = self._selected_project_id > 0

        if is_continuation:
            project_info = project_manager.get_project(self._selected_project_id)
            if not project_info:
                QMessageBox.warning(self, "提示", "所选项目不存在，请重新选择")
                return
            novel_name = project_info["name"]
            male_name = self._male_name.text().strip()
            female_name = self._female_name.text().strip()
            novel_type = project_info.get("genre", "")
            protagonist = ""
            setting = ""
            plot = project_info.get("description", "")
            outline = ""
            master_outline = ""
            context_type = "continuation"
            use_outline_mode = False

            from_index = self._chapter_from.currentData() or 0
            to_index = self._chapter_to.currentData() or 0
            if from_index <= 0:
                QMessageBox.warning(self, "提示", "请选择有效的起始章节")
                return

            chapters_to_generate = list(range(from_index, to_index + 1))
            gen_chapters = len(chapters_to_generate)

            existing_text_parts = []
            existing_chapters = self._existing_chapters_cache
            for ch in existing_chapters:
                content = ch.get("content", "")
                if content:
                    opening = content[:100].replace("\n", " ")
                    closing = content[-200:].replace("\n", " ") if len(content) > 200 else content.replace("\n", " ")
                    existing_text_parts.append(
                        f"【{ch['title']}】{opening}...【结尾】{closing}"
                    )
            existing_project_context = "\n\n".join(existing_text_parts)
        else:
            novel_name = self._novel_name.text().strip()
            if not novel_name:
                QMessageBox.information(self, "提示", "请填写小说名称")
                self._novel_name.setFocus()
                return

            male_name = self._male_name.text().strip()
            female_name = self._female_name.text().strip()
            existing_project_context = ""

            master_outline = self._master_outline.toPlainText().strip()
            use_outline_mode = bool(master_outline)

            if use_outline_mode:
                novel_type = ""
                protagonist = ""
                setting = ""
                plot = ""
                outline = ""
            else:
                novel_type = self._novel_type.currentText().strip()
                protagonist = self._protagonist.toPlainText().strip()
                setting = self._setting.toPlainText().strip()
                plot = self._plot.toPlainText().strip()
                outline = self._outline.toPlainText().strip()

                if not all([novel_type, protagonist, plot]):
                    QMessageBox.warning(self, "提示",
                        "请至少填写小说类型、主角设定和核心剧情。\n"
                        "或者在上方填写「总大纲」直接生成。")
                    return

            gen_chapters = config_manager.get("writing.generate_chapter_count", 10)

        gen_words = config_manager.get("writing.generate_word_per_chapter", 2000)

        self._switch_to_generating_mode()

        context_type = "outline" if use_outline_mode else ("continuation" if is_continuation else "detail")

        raw_style = self._writing_style.currentText()
        raw_style_name = raw_style.split(" - ", 1)[0]
        if raw_style == "（默认）":
            writing_style_text = ""
        elif raw_style_name == "自动文笔":
            writing_style_text = "请根据故事大纲和主题内容，自动选择最适合的文笔风格进行创作（如热血类用简洁有力、言情类用细腻优美、悬疑类用冷峻紧张等）。"
        else:
            style_part = raw_style.split(" - ", 1)
            style_name = style_part[0]
            style_desc = style_part[1] if len(style_part) > 1 else ""
            writing_style_text = f"采用{style_name}文笔风格。{style_desc}"

        context_data = {
            "master_outline": master_outline,
            "novel_type": novel_type,
            "protagonist": protagonist,
            "setting": setting,
            "plot": plot,
            "outline": outline,
            "male_name": male_name,
            "female_name": female_name,
            "writing_style": writing_style_text,
            "gender": self._gender.currentText(),
            "novel_name": novel_name,
            "existing_project_context": existing_project_context,
        }

        self._thread = threading.Thread(
            target=self._generation_worker,
            args=(novel_name, novel_type, context_type, context_data,
                  gen_chapters, gen_words, male_name, female_name,
                  is_continuation),
            daemon=True
        )
        self._thread.start()

    def cancel_generation(self):
        self._cancel_requested = True
        self._cancel_btn.setEnabled(False)
        self._cancel_btn.setText("正在停止...")
        self._progress_status.setText("⏹ 正在停止生成，请等待当前章节完成...")
        self._progress_log.append("⏹ 已请求停止，完成当前章节后将终止...")

    def _generation_worker(self, novel_name, novel_type, context_type,
                           context_data, total_chapters, words_per_chapter,
                           male_name, female_name, is_continuation=False):
        """后台生成线程"""
        try:
            if is_continuation:
                pid = self._selected_project_id
                self._bridge.log.emit(f"📚 基于已有项目《{novel_name}》续写{total_chapters}章...")
                volumes = volume_manager.get_volumes(pid)
                volume_id = volumes[-1]["id"] if volumes else volume_manager.create_volume(pid, "第一卷")
                existing_all = chapter_manager.get_all_chapters_for_project(pid)
                existing_count = len(existing_all)
                gen_base = existing_count
                previous_summaries = []
                for ch in existing_all:
                    content = ch.get("content", "")
                    if content:
                        opening = content[:100].replace("\n", " ")
                        closing = content[-200:].replace("\n", " ") if len(content) > 200 else content.replace("\n", " ")
                        ch_summary = f"【本章内容概要】{opening}...【本章结尾】{closing}"
                        previous_summaries.append(ch_summary)
            else:
                self._bridge.log.emit(f"📚 开始生成小说《{novel_name}》共{total_chapters}章...")

                description = f"AI自动生成的小说"
                if male_name or female_name:
                    description = f"主角：{'、'.join(filter(None, [male_name, female_name]))}"
                if context_type == "detail":
                    description += f"\n类型：{context_data.get('novel_type', '')}\n{context_data.get('plot', '')[:200]}"
                else:
                    description += f"\n基于总大纲生成"

                effective_genre = context_data.get("novel_type", "") or "通用"

                pid = project_manager.create_project(
                    name=novel_name,
                    author="AI创作",
                    genre=effective_genre,
                    description=description,
                    word_goal=total_chapters * words_per_chapter
                )

                volumes = volume_manager.get_volumes(pid)
                volume_id = volumes[0]["id"] if volumes else volume_manager.create_volume(pid, "第一卷")

                existing_chapters = chapter_manager.get_chapters(volume_id)
                for ch in existing_chapters:
                    chapter_manager.delete_chapter(ch["id"])

                previous_summaries = []
                gen_base = 0
            total_words = 0
            max_tokens = int(words_per_chapter * 1.5) + 200
            chapter_details = []

            for loop_idx in range(1, total_chapters + 1):
                if self._cancel_requested:
                    self._bridge.log.emit(f"⏹ 已在第{loop_idx - 1}章处停止生成（已保存）")
                    break

                actual_chapter_num = gen_base + loop_idx
                chapter_title = f"第{actual_chapter_num}章"

                cid = chapter_manager.create_chapter(volume_id, chapter_title)
                if not cid:
                    self._bridge.error.emit(f"创建章节失败：{chapter_title}")
                    return

                chapter_prompt = make_chapter_prompt(
                    context_type=context_type,
                    context_data=context_data,
                    chapter_number=actual_chapter_num,
                    chapter_title=chapter_title,
                    word_count=words_per_chapter,
                    previous_summaries=previous_summaries
                )

                self._bridge.progress.emit(
                    loop_idx, total_chapters,
                    f"正在生成第 {loop_idx}/{total_chapters} 章...",
                    total_words
                )
                self._bridge.log.emit(f"📝 {chapter_title} 约{words_per_chapter}字，AI生成中...")

                collected_tokens = []
                stream_chars = [0]
                last_stream_tick = [time.time()]

                def on_token(token):
                    collected_tokens.append(token)
                    stream_chars[0] += len(token)
                    self._bridge.token_alive.emit()
                    now = time.time()
                    if now - last_stream_tick[0] >= 2:
                        last_stream_tick[0] = now
                        self._bridge.stream_update.emit(
                            actual_chapter_num, total_chapters,
                            stream_chars[0], total_words + stream_chars[0],
                            "📝 AI生成中..."
                        )

                self._bridge.log.emit(f"📞 正在调用AI接口...")
                try:
                    future = self._pool.submit(
                        ai_manager.generate,
                        prompt=chapter_prompt,
                        max_tokens=max_tokens,
                        temperature=0.8,
                        callback=on_token
                    )
                    result = future.result()
                    self._bridge.log.emit(f"📞 AI接口调用成功")
                except concurrent.futures.TimeoutError:
                    self._bridge.log.emit(f"❌ AI接口调用超时")
                    self._bridge.error.emit(
                        f"{chapter_title}生成超时（流式停顿超过{AI_CHAPTER_TIMEOUT}秒）。\n"
                        f"请检查网络连接后重试。"
                    )
                    return
                except Exception as e:
                    self._bridge.log.emit(f"❌ AI接口调用失败：{str(e)}")
                    self._bridge.error.emit(f"{chapter_title}生成异常：{str(e)}")
                    return

                self._bridge.log.emit(f"✅ AI接口调用成功，开始保存...")

                if not result or result.startswith("错误:") or result.startswith("生成失败"):
                    self._bridge.error.emit(f"{chapter_title}生成失败：{result or '结果为空'}")
                    return

                chapter_manager.save_chapter(cid, result)

                word_count = text_processor.count_words(result)
                total_words += word_count
                opening = result[:100].replace("\n", " ")
                closing = result[-200:].replace("\n", " ") if len(result) > 200 else result.replace("\n", " ")
                summary = f"【本章内容概要】{opening}...【本章结尾】{closing}【本章字数:{word_count}字】"
                previous_summaries.append(summary)

                self._bridge.chapter_done.emit(loop_idx, chapter_title, total_words, word_count)
                self._bridge.log.emit(f"✅ {chapter_title}完成 - {word_count:,}字")
                chapter_details.append({"title": chapter_title, "words": word_count})

            self._bridge.log.emit(f"\n🎉 全部完成！总字数：{total_words:,}")
            self._bridge.finished.emit(pid, novel_name, chapter_details)

        except Exception as e:
            logger.error(f"生成线程异常: {e}")
            import traceback
            logger.error(traceback.format_exc())
            self._bridge.error.emit(f"生成过程出错：{str(e)}")

    def _on_progress(self, current_chapter: int, total: int, status_text: str, words: int):
        """进度更新（主线程）"""
        self._progress_status.setText(f"📖 {status_text}")
        self._progress_bar.setMaximum(total)
        self._progress_bar.setValue(current_chapter)
        self._progress_chapter.setText(f"第 {current_chapter}/{total} 章")
        self._progress_words.setText(f"总字数: {words:,} 字")

    def _on_stream_update(self, chapter: int, total: int, current_chars: int, total_words: int, status: str):
        """流式实时进度更新（主线程）"""
        self._progress_status.setText(f"{status}（本{chapter}章已生成约{current_chars}字）")
        self._progress_bar.setMaximum(total * 3)
        self._progress_bar.setValue((chapter - 1) * 3 + (1 if current_chars > 0 else 0))
        self._progress_chapter.setText(f"第 {chapter}/{total} 章")
        self._progress_words.setText(f"总字数: {total_words:,} 字")

    def _on_chapter_done(self, chapter_number: int, title: str, total_words: int, chapter_words: int):
        """单章完成（主线程）"""
        self._progress_bar.setValue(chapter_number)
        self._progress_status.setText(f"✅ 第{chapter_number}章完成（{chapter_words:,}字）")
        self._completed_chapters.append({"num": chapter_number, "words": chapter_words})

    def _on_token_alive(self):
        """AI流式token到达（主线程），更新时间戳"""
        self._last_token_time = time.time()

    def _watchdog_check(self):
        """看门狗检查：流式停顿超时检测"""
        if not self._generating or self._cancel_requested:
            return
        if self._last_token_time == 0:
            return
        elapsed = time.time() - self._last_token_time
        if elapsed > AI_CHAPTER_TIMEOUT and not self._cancel_requested:
            self._cancel_requested = True
            self._bridge.log.emit(f"⏰ AI流式输出已停顿超过{AI_CHAPTER_TIMEOUT}秒，自动终止")
            self._bridge.error.emit(
                f"AI流式输出已停顿超过{AI_CHAPTER_TIMEOUT}秒。\n"
                f"请检查网络连接后重试。"
            )

    def _on_generation_finished(self, pid: int, novel_name: str, chapter_details: list):
        """全部生成完成（主线程）"""
        self._watchdog_timer.stop()
        self._progress_status.setText("✅ 生成完成！")

        total_w = sum(d["words"] for d in chapter_details)
        detail_lines = "\n".join(
            f"  {d['title']}: {d['words']:,}字" for d in chapter_details[:10]
        )
        if len(chapter_details) > 10:
            detail_lines += f"\n  ...等共{len(chapter_details)}章"

        QMessageBox.information(self, "生成完成",
            f"小说《{novel_name}》已生成！\n\n"
            f"共 {len(chapter_details)} 章，{total_w:,} 字\n\n"
            f"章节详情:\n{detail_lines}\n\n"
            f"请在「文件 → 打开项目」查看。")

        self._switch_to_idle_mode()
        self.accept()

        if self._parent_window and hasattr(self._parent_window, 'open_project_by_id'):
            self._parent_window.open_project_by_id(pid)

    def _on_generation_error(self, error_msg: str):
        """生成错误（主线程）"""
        self._progress_status.setText(f"❌ 生成失败")
        QMessageBox.critical(self, "错误", error_msg)
        self._switch_to_idle_mode()

    def closeEvent(self, event):
        if self._generating and not self._cancel_requested:
            reply = QMessageBox.question(
                self, "确认关闭",
                "小说正在生成中，关闭将终止生成。确认关闭？",
                QMessageBox.Yes | QMessageBox.No
            )
            if reply == QMessageBox.No:
                event.ignore()
                return
        self._cancel_requested = True
        super().closeEvent(event)
